#!/bin/bash

#muestra el directorio actual
#echo "La ruta actual es: `pwd`"

#muestra los archivos hallados
#echo "Esta carpeta contiene los siguientes archivos y carpetas: `ls`"

#echo "Estos son los parametros que se pasaron: $@"

#evaluar los parametros para ver si obtengo el push
#si los obtengo entonces llamo a python para que haga
#su trabajo sucio...

#echo "Probando getopt"

push_flag=false

for i
do
    if [ "$i" = "push" ]; then
        echo "-->$i"
        push_flag=true
    fi
done 

git_output=$( git $* )


if [ $push_flag = true ]; then
    ./SocialGit/social.py
    echo "!!!!!!!!!!!!!!"
else
    echo "$git_output"
fi    

